/// Flutter icons MemorMeIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
import 'package:flutter/widgets.dart';

class MemorMeIcons {
  MemorMeIcons._();

  static const _kFontFam = 'MemorMeIcons';

  static const IconData homeunfilled = IconData(
    0xe800,
    fontFamily: _kFontFam,
  );
  static const IconData search = IconData(
    0xe803,
    fontFamily: _kFontFam,
  );
  static const IconData collectionsfilled = IconData(
    0xe804,
    fontFamily: _kFontFam,
  );
  static const IconData collectionsunfilled = IconData(
    0xe805,
    fontFamily: _kFontFam,
  );
  static const IconData homefilled = IconData(
    0xe806,
    fontFamily: _kFontFam,
  );
  static const IconData memoryoutlined = IconData(
    0xe809,
    fontFamily: _kFontFam,
  );
}
